#pragma once
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include <tchar.h>
#include <strsafe.h>
#include <iostream>
#include <cctype> 
#include <vector>
#include <functional>
#include <d2d1.h>
#include <dwrite.h>
#include <windowsx.h>
